include:
  - project: 'common/project'
    file: 'job-commons.yml'

stages:
   - test
   - build

.rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
      allow_failure: false
    - when: manual

.k6_job:
  stage: test
  image: 
    name: nomeDaImageNoDockerRegistryDentroDoGitlab:latest
    entrypoint: ["/bin/sh"]
  when: manual
  script:
    - k6 run --env VARIABLES_ENV=$VARIABLES_ENV --env VU_START=$VU_START --env VU_MIDDLE=$VU_MIDDLE --env VU_FINAL=$VU_FINAL --env DURATION_START=$DURATION_START --env DURATION_MIDDLE=$DURATION_MIDDLE --env DURATION_FINAL=$DURATION_FINAL --env THRESHOLD=$THRESHOLD --env FAIL_REQUESTS=$FAIL_REQUESTS --env INVOICES=$INVOICES $TEST_FILE

build-k6:
    stage: build
    image: node:19-slim
    extends:
      - .rules
    script: 
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker build -t nomeDaImageNoDockerRegistryDentroDoGitlab:latest -f docker/dockerfile .
      - docker push nomeDaImageNoDockerRegistryDentroDoGitlab:latest

payables-load:
  extends:
    - .k6_job
  variables:
    TEST_FILE: /usr/src/app/dist/sponsors/payables/load.test.js

payables-stress:
  extends:
    - .k6_job
  variables:
    TEST_FILE: /usr/src/app/dist/sponsors/payables/stress.test.js

submit-orders-load:
  extends:
    - .k6_job
  variables:
    TEST_FILE: /usr/src/app/dist/operations/orders/load.test.js

submit-orders-stress:
  extends:
    - .k6_job
  variables:
    TEST_FILE: /usr/src/app/dist/operations/orders/stress.test.js
