image: 253882794486.dkr.ecr.us-east-1.amazonaws.com/build-tools:864d3610-node-18

#include:
#  - project: 'fca/architecture/IaC/cloud-digital/common-ci'
#    file: 'job-commons.yml'

# stages:
#   - build


# k6-build:
#   stage: test
#   only:
#     - develop
#     - master
#     - refactor/node-k6
#   script:  
#     - npm run load
