export const ENV_TEST = {
    VU_START: __ENV.VU_START,
    VU_MIDDLE: __ENV.VU_MIDDLE,
    VU_FINAL: __ENV.VU_FINAL,
    DURATION_START: __ENV.DURATION_START,
    DURATION_MIDDLE: __ENV.DURATION_MIDDLE,
    DURATION_FINAL: __ENV.DURATION_FINAL,
    THRESHOLD: __ENV.THRESHOLD,
    FAIL_REQUESTS: __ENV.FAIL_REQUESTS,
    INVOICES: __ENV.INVOICES,
}