default: &defaults
  parallelism: 1
  working_directory: ~/performance-test-api

k6_performance_tests: &k6_performance_tests
  run:
    name: Running k6 tests
    command: |
      docker build -t k6-tests:latest -f docker/dockerfile .
      
      docker run -t k6-tests:latest run --env ENVIRONMENT=NONPROD /usr/src/app/dist/load-people.test.js

version: 2
jobs:
  run_performance_tests:
    <<: *defaults
    # Use `machine` executor because the Docker executor cannot mount volumes
    machine: true
    steps:
      - checkout
      - *k6_performance_tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - run_performance_tests